tasks:
  - before: |
      export PATH="$HOME/bin:$PATH"
      export DFX_VERSION=0.17.0
      echo 'export PATH="$HOME/bin:$PATH"' >> ~/.bashrc
      sudo apt-get install -q -y libunwind-dev
      DFXVM_INIT_YES=true sh -ci "$(curl -fsSL https://sdk.dfinity.org/install.sh)"
      npm i -g ic-mops
      npm install &
      dfx start --background --clean
      open README.md

vscode:
  extensions:
    - dfinity-foundation.vscode-motoko
    - ms-python.python

ports:
  - name: Replica
    port: 4943
    visibility: public
    onOpen: ignore
  - name: Dev Server
    port: 8080
    visibility: public
    onOpen: open-browser
